# Generated by Django 3.2.9 on 2021-11-27 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='File_Fixed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_documento', models.CharField(max_length=2)),
                ('numero_documento', models.IntegerField(max_length=20)),
                ('nombre_cotizante', models.CharField(max_length=100, null=True)),
                ('cargo', models.CharField(max_length=100, null=True)),
                ('anio', models.IntegerField(max_length=4)),
                ('mes', models.IntegerField(max_length=2)),
                ('salario', models.IntegerField(max_length=20, null=True)),
                ('dias_trab', models.IntegerField(max_length=20, null=True)),
                ('dias_incap', models.IntegerField(max_length=20, null=True)),
                ('dias_licen', models.IntegerField(max_length=20, null=True)),
                ('f_ingreso', models.DateField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='File_Header',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_documento', models.CharField(max_length=2)),
                ('numero_documento', models.IntegerField(max_length=20)),
                ('razon_social', models.CharField(max_length=100)),
                ('referencia', models.IntegerField(max_length=100)),
                ('solicitud', models.CharField(max_length=100)),
            ],
        ),
    ]
