# Generated by Django 3.2.9 on 2021-11-27 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file_fixed',
            name='anio',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='file_fixed',
            name='dias_incap',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='file_fixed',
            name='dias_licen',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='file_fixed',
            name='dias_trab',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='file_fixed',
            name='salario',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='file_header',
            name='numero_documento',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='file_header',
            name='referencia',
            field=models.IntegerField(),
        ),
    ]
