# Generated by Django 3.2.9 on 2021-11-27 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0002_auto_20211126_2056'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file_fixed',
            name='mes',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='file_fixed',
            name='numero_documento',
            field=models.IntegerField(),
        ),
    ]
