# Generated by Django 3.2.9 on 2021-12-02 22:04

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0003_auto_20211126_2057'),
    ]

    operations = [
        migrations.AddField(
            model_name='file_fixed',
            name='referencia',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='files.file_header'),
            preserve_default=False,
        ),
    ]
