# Generated by Django 3.2.9 on 2021-12-02 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0004_file_fixed_referencia'),
    ]

    operations = [
        migrations.AddField(
            model_name='file_fixed',
            name='total_dias',
            field=models.IntegerField(null=True),
        ),
    ]
