# Generated by Django 3.2.9 on 2021-12-02 22:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0005_file_fixed_total_dias'),
    ]

    operations = [
        migrations.RenameField(
            model_name='file_fixed',
            old_name='referencia',
            new_name='referencia_id',
        ),
    ]
