# Generated by Django 3.2.9 on 2021-12-02 22:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0006_rename_referencia_file_fixed_referencia_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='file_fixed',
            old_name='referencia_id',
            new_name='referencia',
        ),
    ]
